Remove the priority graph clear at slot boundaries (#207) (#208)
Problem

Panic

[2025-09-16T18:57:51.938244000Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solBamSched" one=1i message="panicked at /Users/ebinmathews/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/prio-graph-0.3.0/src/prio_graph.rs:189:13:
    node must exist" location="/Users/ebinmathews/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/prio-graph-0.3.0/src/prio_graph.rs:189:13" version="3.1.0 (src:6dd239ce; feat:128318206, client:Bam)"
Summary of Changes

Remove prio graph clear at slot boundaries as it's causing panic.